# Build only merge request and default branch
# and branches start with (develop).
# save time for quick demo pushes
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^develop/

humble-gcc-coverage:
  image:
    name: ros:humble-ros-core

  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .ccache/

  variables:
    ISOLATION: "shell"
    ROS_DISTRO: "humble"
    CCACHE_DIR: "${CI_PROJECT_DIR}/.ccache"
    TARGET_CMAKE_ARGS: "-DCMAKE_C_FLAGS='--coverage' -DCMAKE_CXX_FLAGS='--coverage'"

  script:
    - apt-get update && apt-get install -y git curl libcurl4-openssl-dev
    - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
    - .industrial_ci/gitlab.sh
    # Upload coverage report
    - ./coverage.sh ci
    - curl -Os https://uploader.codecov.io/latest/linux/codecov
    - chmod +x codecov
    - ./codecov -f ./coverage.info
  coverage: '/Total:\|(\d+\.?\d+\%)/'

humble-clang:
  image:
    name: ros:humble-ros-core

  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .ccache/

  variables:
    ISOLATION: "shell"
    ROS_DISTRO: "humble"
    ADDITIONAL_DEBS: "clang lld"
    CCACHE_DIR: "${CI_PROJECT_DIR}/.ccache"
    CC: "clang"
    CXX: "clang++"
    TARGET_CMAKE_ARGS: "-DCMAKE_EXE_LINKER_FLAGS=-fuse-ld=lld -DCMAKE_MODULE_LINKER_FLAGS=-fuse-ld=lld -DCMAKE_SHARED_LINKER_FLAGS=-fuse-ld=lld"

  script:
    - apt-get update && apt-get install -y git curl libcurl4-openssl-dev
    - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
    - .industrial_ci/gitlab.sh

jazzy-gcc:
  image:
    name: ros:jazzy-ros-core

  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .ccache/

  variables:
    ISOLATION: "shell"
    ROS_DISTRO: "jazzy"
    CCACHE_DIR: "${CI_PROJECT_DIR}/.ccache"

  script:
    - apt-get update && apt-get install -y git curl libcurl4-openssl-dev
    - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
    - .industrial_ci/gitlab.sh

jazzy-gcc-asan:
  image:
    name: ros:jazzy-ros-core

  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .ccache/

  variables:
    ISOLATION: "shell"
    ROS_DISTRO: "jazzy"
    CCACHE_DIR: "${CI_PROJECT_DIR}/.ccache"
    TARGET_CMAKE_ARGS: "-DCMAKE_C_FLAGS='-fsanitize=address' -DCMAKE_CXX_FLAGS='-fsanitize=address'"

  script:
    - apt-get update && apt-get install -y git curl libcurl4-openssl-dev
    - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
    - .industrial_ci/gitlab.sh

jazzy-gcc-tsan:
  image:
    name: ros:jazzy-ros-core

  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .ccache/

  variables:
    ISOLATION: "shell"
    ROS_DISTRO: "jazzy"
    CCACHE_DIR: "${CI_PROJECT_DIR}/.ccache"
    TARGET_CMAKE_ARGS: "-DCMAKE_C_FLAGS='-fsanitize=thread -O2 -g -fno-omit-frame-pointer' -DCMAKE_CXX_FLAGS='-fsanitize=thread -O2 -g -fno-omit-frame-pointer'"

  script:
    - apt-get update && apt-get install -y git curl libcurl4-openssl-dev
    - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
    - .industrial_ci/gitlab.sh

jazzy-clang:
  image:
    name: ros:jazzy-ros-core

  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .ccache/

  variables:
    ISOLATION: "shell"
    ROS_DISTRO: "jazzy"
    ADDITIONAL_DEBS: "clang lld"
    CCACHE_DIR: "${CI_PROJECT_DIR}/.ccache"
    CC: "clang"
    CXX: "clang++"
    TARGET_CMAKE_ARGS: "-DCMAKE_EXE_LINKER_FLAGS=-fuse-ld=lld -DCMAKE_MODULE_LINKER_FLAGS=-fuse-ld=lld -DCMAKE_SHARED_LINKER_FLAGS=-fuse-ld=lld"

  script:
    - apt-get update && apt-get install -y git curl libcurl4-openssl-dev
    - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
    - .industrial_ci/gitlab.sh

# Build API Documentation
doxygen-docs:
  image: ubuntu:latest

  before_script:
    - apt-get -qq update
    - apt-get -y -qq install doxygen graphviz

  script:
    - (mkdir -p docs/doxygen/build && cd ./.doxygen && doxygen)

  artifacts:
    paths:
      - docs/doxygen/build/html/
    expire_in: 1 day

# Build Sphinx Documentation
sphinx-docs:
  image: ubuntu:22.04

  before_script:
    - apt-get -qq update

    # Install Python3 dependencies
    - apt-get install -y -qq python3-pip python3-dev
    - python3 -m pip install --upgrade setuptools

    # Install Sphinx
    - python3 -m pip install --upgrade sphinx sphinx-rtd-theme myst_parser recommonmark

    # Install Lint tools
    - DEBIAN_FRONTEND="noninteractive" apt-get install -y -qq enchant-2 git
    - python3 -m pip install --upgrade doc8 pyenchant sphinxcontrib-spelling

  script:
    # Make html
    - make -C docs/sphinx html
    # Run Doc8 Lint
    - doc8 docs/sphinx --ignore-path docs/sphinx/build --max-line-length 999
    # Check Spelling
    - make -C docs/sphinx spelling
    - find . -name *.spelling -exec cat {} \;
    - sh -c "! find . -name *.spelling | grep -q ."
  artifacts:
    paths:
      - docs/sphinx/build/html/
    expire_in: 1 day


