# Build only merge request and default branch
# and branches start with (develop).
# save time for quick demo pushes
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^develop/

humble-nightly-gcc-coverage:
  image:
    name: registry.gitlab.com/rosi-ap/rosi-ap_infrastructure/rosiap_docker_images/ros:rmf-humble-nightly

  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .ccache/

  variables:
    ISOLATION: "shell"
    ROS_DISTRO: "humble"
    CCACHE_DIR: "${CI_PROJECT_DIR}/.ccache"
    UPSTREAM_WORKSPACE: "deps.repos"
    TARGET_CMAKE_ARGS: "-DCMAKE_C_FLAGS='--coverage' -DCMAKE_CXX_FLAGS='--coverage'"

  script:
    - apt-get update && apt-get install -y git
    - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
    - .industrial_ci/gitlab.sh
    # Upload coverage report
    - ./coverage.sh ci
    - curl -Os https://uploader.codecov.io/latest/linux/codecov
    - chmod +x codecov
    - ./codecov -f ./coverage.info

humble-nightly-gcc-asan:
  image:
    name: registry.gitlab.com/rosi-ap/rosi-ap_infrastructure/rosiap_docker_images/ros:rmf-humble-nightly

  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .ccache/

  variables:
    ISOLATION: "shell"
    ROS_DISTRO: "humble"
    CCACHE_DIR: "${CI_PROJECT_DIR}/.ccache"
    UPSTREAM_WORKSPACE: "deps.repos"
    TARGET_CMAKE_ARGS: "-DCMAKE_C_FLAGS='-fsanitize=address' -DCMAKE_CXX_FLAGS='-fsanitize=address'"

  script:
    - apt-get update && apt-get install -y git
    - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
    - .industrial_ci/gitlab.sh

humble-nightly-gcc-tsan:
  image:
    name: registry.gitlab.com/rosi-ap/rosi-ap_infrastructure/rosiap_docker_images/ros:rmf-humble-nightly

  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .ccache/

  variables:
    ISOLATION: "shell"
    ROS_DISTRO: "humble"
    CCACHE_DIR: "${CI_PROJECT_DIR}/.ccache"
    UPSTREAM_WORKSPACE: "deps.repos"
    TARGET_CMAKE_ARGS: "-DCMAKE_C_FLAGS='-fsanitize=thread -O2 -g -fno-omit-frame-pointer' -DCMAKE_CXX_FLAGS='-fsanitize=thread -O2 -g -fno-omit-frame-pointer'"

  script:
    - apt-get update && apt-get install -y git
    - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
    - .industrial_ci/gitlab.sh

humble-nightly-clang:
  image:
    name: registry.gitlab.com/rosi-ap/rosi-ap_infrastructure/rosiap_docker_images/ros:rmf-humble-nightly

  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .ccache/

  variables:
    ISOLATION: "shell"
    ROS_DISTRO: "humble"
    CCACHE_DIR: "${CI_PROJECT_DIR}/.ccache"
    UPSTREAM_WORKSPACE: "deps.repos"
    CC: "clang"
    CXX: "clang++"
    TARGET_CMAKE_ARGS: "-DCMAKE_EXE_LINKER_FLAGS=-fuse-ld=lld -DCMAKE_MODULE_LINKER_FLAGS=-fuse-ld=lld -DCMAKE_SHARED_LINKER_FLAGS=-fuse-ld=lld"

  script:
    - apt-get update && apt-get install -y git
    - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
    - .industrial_ci/gitlab.sh

# Build API Documentation
doxygen-docs:
  image: ubuntu:latest

  before_script:
    - apt-get -qq update
    - apt-get -y -qq install doxygen graphviz

  script:
    - (mkdir -p docs/doxygen/build && cd ./.doxygen && doxygen)

  artifacts:
    paths:
      - docs/doxygen/build/html/
    expire_in: 1 day

